version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: traveloair_postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=traveloair
      - POSTGRES_USER=root
    privileged: true
